Vagrant.configure("2") do |config|
  config.vm.box = "crappygraphix/nixos-19.03-x86_64"
  config.vm.box_version = "1.0.0"
  config.vm.network 'private_network', ip: "192.169.1.1"
  config.vm.network 'forwarded_port', guest: 8888, port: 8888
  config.vm.synced_folder "./share", "/vagrant", folder_options

  config.vm.provision :nixos,
    run: 'always',
    path: 'configuration.nix',
   verbose: true
end
