#!/usr/bin/env zsh

function ghi_close() {
    if [[ "$1" = <-> ]]; then
        echo "Closing issue #${1}"
        ghi close "$1"
    else
        echo "Opening and closing issue: ${1}"
        ghi close $(ghi open -m "$1" -L "in progress" | head -n 1 | awk 'match($0, /[0-9]+/){print substr($0, RSTART, RLENGTH)}') &&
        echo "Assigning issue $1"
        ghi assign $1 -u $(git config --global user.name)
    fi
}

ghi_close $@
