#!/usr/bin/env zsh

# Open an issue in each maven-convention following project
#
# Example:
# ghi_opens "some issue"

function ghi_opens(){
    for project in *(e:'[[ -e $REPLY/src/main ]]':); do
        ghi open "[$project] $1"
    done
}

ghi_opens $@
