#!/usr/bin/env zsh

function ghi_epic_issue_open() {
    local MILESTONE=$(<.milestone)
    if [[ -n $MILESTONE ]]; then
        echo "Attaching issue to $MILESTONE" &&
        ghi open $1 -M $MILESTONE
    else
        ghi open $1
    fi
}

ghi_epic_issue_open $@
