name: "Build"
on:
  pull_request:
  push:
    branches:
      main
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # - uses: cachix/cachix-action@v10
      #   with:
      #     name: peel
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'        
      - run: nix flake check
      - run: nix build .#nixosConfigurations.wrkvm
      - run: nix build .#vmwareImage.aarch64-linux
      - run: nix build .#vmwareImage.x86_64-linux
      - uses: actions/upload-artifact@v2
        with:
          name: vmware
          path: ./result/*.vmdk
